### ISSUE TITLE
[Insight] Sensitive data should not be present in non-parameter configuration files

### ISSUE THREAD

**Issue by Nyholm** [symfonyse/symfony.se#28]
**[in app/config/security.yml, line 13](https://github.com/symfonyse/symfony.se/blob/master/app/config/security.yml#L13)**

> A sensitive data has been detected in your configuration file (`password` parameter). You should consider storing it in a single parameter file.

```

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/b2701cbf-5de2-4b56-bad4-fde2b14f86b1/analyses/1)_
